import { AlertTriangle, BarChart3, Flag, ShieldCheck, Users } from "lucide-react";

const reports = [
  { id: "R-018", type: "公开介绍中出现联系方式", target: "用户：夏日岛", status: "等待回应" },
  { id: "R-017", type: "资料信息需要进一步确认", target: "用户：橘子汽水", status: "了解中" },
  { id: "R-016", type: "头像可能不符合展示约定", target: "用户：North", status: "暂不展示" },
];

export default function AdminPage() {
  return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-800 sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold tracking-[.2em] text-sky-700">线上组队</p><h1 className="mt-1 text-3xl font-black">社区维护空间</h1></div><span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-800">演示模式 · 部署后使用 GitHub 登录</span></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Users} label="愿意公开的介绍" value="128" /><Metric icon={ShieldCheck} label="已确认校园身份" value="0" /><Metric icon={Flag} label="等待回应的反馈" value="2" /><Metric icon={BarChart3} label="已经相遇的小队" value="19" /></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">社区反馈</h2><p className="mt-1 text-xs text-slate-500">在保护各方的前提下了解情况，并留下处理说明</p></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">编号</th><th className="p-4">反馈内容</th><th className="p-4">相关介绍</th><th className="p-4">状态</th><th className="p-4">操作</th></tr></thead><tbody>{reports.map((r) => <tr key={r.id} className="border-t border-slate-100"><td className="p-4 font-mono text-xs">{r.id}</td><td className="p-4 font-medium">{r.type}</td><td className="p-4 text-slate-500">{r.target}</td><td className="p-4"><span className="rounded-full bg-amber-50 px-2 py-1 text-xs text-amber-800">{r.status}</span></td><td className="p-4"><button className="text-sm font-bold text-sky-700">了解详情</button></td></tr>)}</tbody></table></div></section><aside className="space-y-4"><div className="card p-5"><h2 className="font-bold">本届选寝日期</h2><p className="mt-2 text-sm text-slate-500">2026年8月1日</p><p className="mt-3 text-xs leading-5 text-slate-400">本届选寝结束 30 天后，个人介绍、联系方式与组队数据会自动清理。</p><button className="button button-secondary mt-4 w-full">调整日期</button></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><AlertTriangle className="mb-2 size-4" />正式开放维护入口前，需要先配置 GitHub 登录，并确认管理员账号。</div></aside></div></div></main>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string }) { return <div className="card flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-2xl bg-sky-50 text-sky-700"><Icon className="size-5" /></span><div><strong className="text-2xl text-sky-950">{value}</strong><span className="block text-xs text-slate-500">{label}</span></div></div>; }
